name = "Fabulously Optimized"
author = "robotkoer"
version = "10.1.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "152fb12a8f16915bdde72fbaafcf519f0de32e9ca7506257dced3f47de571d90"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
