name = "Fabulously Optimized"
author = "robotkoer"
version = "10.1.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15c0125a210859d3ab8033fdbe452123f830e218aafc905f1a6e5c19de26270a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
