name = "Fabulously Optimized"
author = "robotkoer"
version = "10.1.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef3a5e915fe09321c95f9123f0444c95c850f76514e5e99738fb7b2a1df5579d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
