name = "Fabulously Optimized"
author = "robotkoer"
version = "6.0.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12fcf727d3becc4aad1441f9b74728873c3643a31d56f320e4d26d72d73711f2"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
