name = "Fabulously Optimized"
author = "robotkoer"
version = "6.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a63ce0e614a0d650e19d013386c153a319e7794636462c206372590bc01d989b"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
