name = "Fabulously Optimized"
author = "robotkoer"
version = "6.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66576ce9b27734a956606103b8c570ba8d9450d230f01bedb0b579610f5f2565"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
