name = "Fabulously Optimized"
author = "robotkoer"
version = "6.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ab4e21ca84e1e84dc70521161664ee421a8f767a5a9dd0c06493c58da19bdcb"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
