name = "Fabulously Optimized"
author = "robotkoer"
version = "6.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eba3ccfe551219fee1f4948324ce6632a13ee9a050b5def543b7745070b221c"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
