name = "Fabulously Optimized"
author = "robotkoer"
version = "5.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b403a7d03c05ebfc5cc5fcde3d0b525a2c71460607784ad76d11acb09780179"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
