name = "Fabulously Optimized"
author = "robotkoer"
version = "5.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c8542725f99cd1a118bb9af46af1c67661881ffbb36ac9175edfc2870bba877"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
