name = "Fabulously Optimized"
author = "robotkoer"
version = "5.4.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0e605e961752c6eb3a105562d698562e3a95f2414c771c21f314da0e8fba548"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
