name = "Fabulously Optimized"
author = "robotkoer"
version = "5.5.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16eebe254897e9c0f05131751251f637edda2beaf3d82636fed5e1219983d8b2"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
