name = "Fabulously Optimized"
author = "robotkoer"
version = "5.4.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "399b3dd509913f78a34ee5f05fc43c8081eeb01c831be55d2b37b7a3b7e8f59b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
