name = "Fabulously Optimized"
author = "robotkoer"
version = "6.6.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c9bc0d13a6b4f5f40cf7ec51b823f88b563b203021f35ac6a3a784c8cec46db"

[versions]
fabric = "0.16.10"
minecraft = "1.21.5"
