name = "Fabulously Optimized"
author = "robotkoer"
version = "9.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e7de88c5989a175429ea90086fe5f845bdcedaeee4e014967c35679c6bb6af1"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
