name = "Fabulously Optimized"
author = "robotkoer"
version = "6.6.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b120e9ab98ff13e8e4befa14a485e988ff035b8fcb49a098ea6030cc671573d"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
