name = "Fabulously Optimized"
author = "robotkoer"
version = "6.6.0-alpha.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c840287dcc8a03ac70e28a8d37e8c2b05281745cd04c042779d18391f03a745b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
