name = "Fabulously Optimized"
author = "robotkoer"
version = "9.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15f60df914998fb2ad8ced2ca5d05b325eb80921ce2f6fb790e3a14ca4d7c01a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
