name = "Fabulously Optimized"
author = "robotkoer"
version = "9.0.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5132183834fb6664bf4c6c94fad0be856762dcf0b94d5c06bc9593a1c41210c1"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
