name = "Fabulously Optimized"
author = "robotkoer"
version = "9.0.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fa04945de3df876bdeeca016ed5524e2b2d52c62ca656d6a9aeb18c8fdb1896"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
