name = "Fabulously Optimized"
author = "robotkoer"
version = "9.0.0-beta.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c8a72f60f79ea57cea85ff03acc2bbe4e734500e2d16909ab9c6ae162111f2e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
