name = "Fabulously Optimized"
author = "robotkoer"
version = "6.6.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c231f31a74e920710c50773fabb05290cc8636b6b8a47e462b8b39b66737e6d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.5"
