name = "Fabulously Optimized"
author = "robotkoer"
version = "6.4.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "649558c8692de0292dd73cabd24bab261692975570e2ac141f4f8f95e599db81"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
