name = "Fabulously Optimized"
author = "robotkoer"
version = "6.4.0-alpha.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aec1f79d09b22a6d71ef4646a80c8e326b2612cfddd0a1cba334691a3d42e0e2"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
