name = "Fabulously Optimized"
author = "robotkoer"
version = "6.4.0-alpha.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92eecd4e06804468673464f46d1bdedfd1ccc2a1c2b3327eb2ab3bd0c733121a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
