name = "Fabulously Optimized"
author = "robotkoer"
version = "5.8.0-beta.9-a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3edd14cc91692233d49fd2765782d24cd2a39e473b293f30249574c530042a6e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
