name = "Fabulously Optimized"
author = "robotkoer"
version = "5.8.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8525e473aee73749660f072900d419225c7ee3748c48e19994e8c0575d1d152"

[versions]
fabric = "0.15.2"
minecraft = "1.20.4"
