name = "Fabulously Optimized"
author = "robotkoer"
version = "5.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af7d48c50662ff69adc5c886601b628137b6356653b77329632374dced36599d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
