name = "Fabulously Optimized"
version = "4.2.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebcf30ac3309bb7348313f11be3c58de39f99b8428a24172ca8eed48842b0946"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
