name = "Fabulously Optimized"
author = "robotkoer"
version = "4.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51ad442417b32d12711b462bcfcf2e787b275a10bb017b108eb0ba0153065d1c"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
