name = "Fabulously Optimized"
author = "robotkoer"
version = "4.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdf00d4b7c10b057bfec3aea81735e0304fe1f6aaf3fc29616887339f1a5a0fe"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
