name = "Fabulously Optimized"
version = "4.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f86b5375d6d56d6c069dff96a66ceb13f856e83da025f313b0593bcf0f7329ee"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
