name = "Fabulously Optimized"
author = "robotkoer"
version = "4.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09ad7f84562014227635545705f33106a493456b891806d4ab2a80480efe8a33"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
