name = "Fabulously Optimized"
author = "robotkoer"
version = "4.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ac85f6e34ddc607d842c3457d63a8bf618d78b4f8033d5c54de259d9bda54d4"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
