name = "Fabulously Optimized"
author = "robotkoer"
version = "4.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fad20d9979dbcea0582bb7021475c3ebffcf9356b3035ddfd7ba228606600b7"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
