name = "Fabulously Optimized"
version = "1.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "187aa8d71ff159b17a991d90f0013c7761fc806effe768fe745dffeb95e6dd98"

[versions]
fabric = "0.13.1"
minecraft = "1.16.5"
