name = "Fabulously Optimized"
version = "1.12.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f37fba18fcd9d8ff7d1550efed3f3113e0f0268b6c573a2c5c62066b3884ada0"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
