name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"
version = "1.11.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea7641ed52404c785692206266cd01c2352eda5cce09e8d96468854d165b4f88"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
