name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2222edd9899bd12ecbbdc2353695e6ebfe23aa14eaa0bedaa9c40b94afce0a84"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
