name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f909a92a12cd50fcadd685fe4afae2ae45a635ce883fc252d22f887584f5080"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
