name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae4288d4e726da32b7fe6f47fc9d1b01ae6ec78585a1d109173df7425f1b7b2d"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
