name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43d785538fea7a57a4623d929c1eeef869b88a39619770e87681853c1f56bb9b"

[versions]
fabric = "0.12.11"
minecraft = "1.16.5"
