name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2bce804670d24de76872d1694f29e0fdfacbdc59089f224f601e90ec0fe59cf"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
