name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-beta.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eee01466561f7bf2d1a661ce301446e5e25a7f3ae797be66221348b6dd5d71c3"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
