name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "319c21a953a9dfb3712c2e92e06f2e177693db5ee98ea33c3b29e0f118df1c6b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
