name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27fdda10006fb81811bae9a6d96c0c7eb71e7908bd1cdedb894662cfedbad638"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
