name = "Fabulously Optimized"
author = "robotkoer"
version = "8.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8021b80eec6ca38ef51831fbaf62709da6c0f63d3d47b44200f408b17b05b4d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
