name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ea082b67ee5427c2404fd182dde2c38d8a00978e93be14831fcf716ad59920c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
