name = "Fabulously Optimized"
author = "robotkoer"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ea02f4ead2285b803fc30450babf6e77b4b6b1c1b5c0cff3f5352c508f45459"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
