name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94dcd4b4a1afb84a71bed9060fa670d7cee943ff444880c86fd09125db41d925"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
