name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-beta.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "664eeaf6bc8e09954feab7153a3990dd7b32bfd2dc2deaf4299a26661dad6ad9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
