name = "Fabulously Optimized"
author = "robotkoer"
version = "8.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff211cee474e10af0c0e61bee3914fa54214ee77f73e05fa2bdc90c08678a867"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
