name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a9d46d04af2d11928ec918a07554c75853eb4cfb9df0c9451008f9181c09bd4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
