name: Bug report
description: Report an issue with the modpack
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Before reporting an issue, [please search](https://github.com/Fabulously-Optimized/fabulously-optimized/issues) to make sure it has not already been reported. 

- type: textarea
  attributes:
    label: Describe the bug
    description: Describe your issue. Add crashlogs or launcher logs if you have them.
  validations:
    required: true

- type: input
  attributes:
    label: Modpack version
    description: What version of the modpack are you using?
    placeholder: Find it in the bottom right corner of the main menu
  validations:
    required: true

- type: dropdown
  attributes:
    label: Launcher
    description: Which launcher are you using?
    options:
      - Curseforge Launcher
      - MultiMC
      - MultiMC (auto-update)
      - GDLauncher
      - Minecraft Launcher (vanilla)
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Other things
    options:
      - I updated FO to a newer version (mention, what version to what version)
      - I removed or added some mods (mention, which ones)
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Additional context
    description: Screenshots, video or any other information. If it is a crash, please post it to [Pastebin](https://pastebin.com) and add a link here.
    placeholder: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
