name = "Fabulously Optimized"
author = "robotkoer"

[[Resource]]
name = "Mod Menu Helper"
filename = "Mod Menu Helper.zip"
action = "override"

[[Resource]]
name = "Chat Reporting Helper"
filename = "Chat Reporting Helper.zip"
action = "override"

[[File]]
name = "Copy all 3 folders and add Sodium!"
filename = "Copy all 3 folders and add Sodium!.url"
action = "remove"
