name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0c659078fdfba158e6915738725939d0107990bdbd5bb20f0a07206babdbdc4"

[versions]
fabric = "0.11.6"
minecraft = "1.17"
