name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5570baa25f3788ca8877b16fd7f28006f9acca7617c5e2c40ad71893de7a77f6"

[versions]
fabric = "0.11.6"
minecraft = "1.17"
