name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5715e36625150ce4ccb8ebb5ce66978498fa06daaf9dca0db8ef2988598dc31d"

[versions]
fabric = "0.11.6"
minecraft = "1.17"
