name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c3acad62ae3e2477517865913fe9e1ea2fcf7ecc75584588fa09e78034483cf"

[versions]
fabric = "0.11.6"
minecraft = "1.17"
