name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7e2fff1871bab4481abd45288be9287cb82630fdd9f8b27b0db9b51f7abc6d7"

[versions]
fabric = "0.11.6"
minecraft = "1.17"
