name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d4ce4ee0f219f3e06f2adf4a5e67479dd2837ac4112f159f2eeed5ce8de063c"

[versions]
fabric = "0.11.6"
minecraft = "1.17"
