name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81e72e4dcb9376189950e7c958f38bbb120daca8246e1bde735b8d6b4271a522"

[versions]
fabric = "0.11.6"
minecraft = "1.17"
