name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90241e9a5113c43c30c8499c3a0d2181ef3afb0ac3029fdb5480942024444ac1"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
