name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1a18364a2780c45389f53828efa134520dedfb7602f4a01a7021696b3cb57bf"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
