name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-alpha.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "114a0ca2bae8101688c06e22d020e86644d5dc81400f34f8a1317bd85bdd9266"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
