name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "907cac7b8fac86a7e6e2d39794e0728bf748c824001bab54bf31b8b5abe04d61"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
