name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c774f1d66cabaa9a0c759b8f71326bf959688f2fe10c50a628b89f9a10d61457"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
