name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-alpha.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ac5cde4acf78a9e1b443ae1a66f3e241d8f97a96d3cd0f8faa8568e0c44c998"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
