name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-alpha.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bde145339b0d20d217c50419736db66e039a3b8928dbfef4bf2d46b36e0e5105"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
