name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-alpha.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "171c26873b5a9e0d3ed06a9556b1fbab6503d6686d5d38bc36407139f98d7d4a"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
