name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47ee0da72b7b675773a77a5c09aec61ee88ac6ea854a9bc5db3c052ab88d4ad6"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
