name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-beta.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "491f728c654bf82be604069430e4fc50e1a9a9d12ff8c900927c9ef08fe7a418"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
