name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b7a83b7562c10259b902b6fcfea69113625da99547ec36f32998c1a53783586"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
