name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfc9fd106a1164a1d6c35268b68f40c98673254846e0bcf6884e6da4accd216c"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
