name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f54f6d8e88b4dfc195f5f6c76d2f3c6dc009e7db0d3b12ceeb0c39efd1307b55"

[versions]
fabric = "0.12.11"
minecraft = "1.18"
