name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83eec15e1d6faef3399f6dc67d88dde1a95f4991776e747f9ee7feb8db069195"

[versions]
fabric = "0.12.11"
minecraft = "1.18"
