name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"
version = "3.0.0-alpha.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "732714a68865d3577d65c873829c0e3c6094f3dbac0f9fc580dc3aba8586a83d"

[versions]
fabric = "0.12.12"
minecraft = "1.18"
