name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20a2ebccc15c3ad8322a10ca39821060422185906b35de68a81dcb4fd0b7fe66"

[versions]
fabric = "0.12.11"
minecraft = "1.18"
