name = "Fabulously Optimized"
author = "robotkoer"
version = "6.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1359fecec842d29b51c1e8a6ea6ccce928522447c05b35e97b482b852c95ab44"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
