name = "Fabulously Optimized"
author = "robotkoer"
version = "10.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac69052daa09d030bb2cf131e699af7b299594cb98d7d300779c9c8e23276971"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
