name = "Fabulously Optimized"
author = "robotkoer"
version = "10.1.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a11e08664583abfa636a4c603264bc19c0ddd6b5498ad667a5b168565f30117"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
