name = "Fabulously Optimized"
author = "robotkoer"
version = "10.2.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eac2ceba3b3453ceb3323b2fa1d6cce91fda4f02b0e040060c91b3230580acfc"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
