name = "Fabulously Optimized"
author = "robotkoer"
version = "10.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa31d799da797dae6f4437a9a9e427b5d740cfad5b88d6b7846997806f07372"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
