name = "Fabulously Optimized"
author = "robotkoer"
version = "10.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd9fde164041d04eab13550dbe68bdf6ba31edf413d4721f3266696a838b69fc"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
