name = "Fabulously Optimized"
version = "2.6.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d268f7a55669d13c79b820fde82ec395efe8b1e36829bd9cd797095ec61e936c"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
