name = "Fabulously Optimized"
version = "2.6.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47c8531d2c44595b3a02db74afc688a166e25d65cbbacea14f8cd1fde3cbac48"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
