name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9393c0ca8d28587594b2c0899e91aad8ab7bde0dd2dfb976279438b48ddd7747"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
