name = "Fabulously Optimized"
version = "2.7.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3199423aeada5eb72266e5751480f560e5c5efd0ce87cf2a907e69778adbd220"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
