name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcc445ee077e001c0f72d50f07b6ce616dbc061c7284e0c165f1a12173fc5a5e"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
