name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "234ff88afcefe56d8adf985fd4a8e70bc43cd88b4ab8ce3fa81274111ae8de32"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
