name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da06f1acdf6c76cd746f09eb8cc448e64a033c8eb493f03ff1691855578ae0af"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
