name = "Fabulously Optimized"
version = "2.7.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a592e1e5364115d307f1a4db55c54b2239d227efa6376c51084721396db8531f"

[versions]
fabric = "0.13.1"
minecraft = "1.17.1"
