name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d27573d4ae6fb8e500c1e6975afc854accaf7114a7bf6e6683b4a3077f758cdc"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
