name = "Fabulously Optimized"
version = "2.7.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f56f576ead8bdeca24fe280ecf017c3a5ba35557cc13051bd825545ce6e44ef"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
