name = "Fabulously Optimized"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b74656ed2e45e2d4126a73f6aa9dd373f18636abfe01fa2910bda4157d0c270"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
