name = "Fabulously Optimized"
author = "robotkoer"
description = "Improve your graphics and performance with this simple modpack. Experimental releases on Modrinth!"

[[Resource]]
name = "Cloth Config v6"
filename = "cloth-config-6.2.62-fabric.jar" 
url = "https://cdn.modrinth.com/data/9s6osm5g/versions/6.2.57+fabric/cloth-config-6.2.57-fabric.jar"

[[Resource]]
name = "DCCH"
filename = "DCCH-2.0+1.17.jar" 
url = "https://cdn.modrinth.com/data/sUbMm93i/versions/2.0+1.17/DCCH-2.0+1.17.jar"

[[Resource]]
name = "Farsight Mod"
filename = "farsight.fabric-1.18-1.9.jar" 
action = "remove"

[[Resource]]
name = "Mod Menu Helper"
filename = "Mod Menu Helper.zip"
action = "override"
