name = "Fabulously Optimized"
author = "robotkoer"
version = "3.8.2-mr.1"
description = "Improve your graphics and performance with this simple modpack. Experimental releases on Modrinth!"

[[Resource]]
name = "Cloth Config v6"
filename = "cloth-config-6.2.62-fabric.jar" 
url = "https://cdn.modrinth.com/data/9s6osm5g/versions/6.2.57+fabric/cloth-config-6.2.57-fabric.jar"

[[Resource]]
name = "DCCH"
filename = "DCCH-2.0+1.17.jar" 
url = "https://cdn.modrinth.com/data/sUbMm93i/versions/2.0+1.17/DCCH-2.0+1.17.jar"

[[Resource]]
name = "Fabric Language Kotlin"
filename = "fabric-language-kotlin-1.7.2%2Bkotlin.1.6.20.jar" 
url = "https://cdn.modrinth.com/data/Ha28R6CL/versions/1.7.2+kotlin.1.6.20/fabric-language-kotlin-1.7.2%2Bkotlin.1.6.20.jar"

[[Resource]]
name = "Farsight Mod"
filename = "invalid.jar" 
url = "https://github.com/download-from-curseforge-directly.jar"

[[Resource]]
name = "Mod Menu Helper"
filename = "invalid.jar" 
url = "https://github.com/bundled-in-the-pack-already.jar"
