name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc99be592380f160ee45b82373d5271e9300e87005a02bffd42f6c7ef2ee9c8d"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"
