name = "Fabulously Optimized"
version = "3.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b404141dcf4d2d96551dd7d1c032d18aa223ab65ae6ba40a1bc6246b6c390abc"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
