name = "Fabulously Optimized"
version = "3.1.0-beta.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c7a26d92f25817647bda7201b067bd32a201c52ed92ff8ed0dad0b242f4c3cb"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
