name = "Fabulously Optimized"
version = "3.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd27fcd10bb326de57ad945b6aa18385e962e013f1203905f0b2cecb097aea17"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
