name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63812f3d3fa05c9c2b2a94daf36d8476863a305b03297f11218b59bf90aff46b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
