name = "Fabulously Optimized"
version = "3.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7f9941f433af6e230e9b270aa786707d328a63802151e9aa209a5b37ad1f6f2"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
