name = "Fabulously Optimized"
version = "3.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "383bbfb9f0388fc9e6c251e8847105386d9beff1e755a641c3113656b1d61b96"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
