name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eef3c4e01a7bac477e2bddcf41d02a9e5026c17e54b7ddbf2efbb2d8df76b2c0"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
