name = "Fabulously Optimized"
version = "3.2.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a43c39a2349799cdde73b6eda926fd239de2754a4e39339c0298dc4f338fe3a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
