name = "Fabulously Optimized"
version = "3.1.0-alpha.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ded097d63d29957860e7c6a8ca771de5290c27e34fb0016902aefb9d8ce0b92"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
