name = "Fabulously Optimized"
author = "robotkoer"
version = "5.1.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd744adb90ef46b72f10f983ebe5112c9d7431e8e0cfc16a5fdf6f6a12fb50c6"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
