name = "Fabulously Optimized"
author = "robotkoer"
version = "5.1.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bd88364f81c6427a182356241c00641ff282ccd7eb6ff0407fef09e9f189cce"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
