name = "Fabulously Optimized"
author = "robotkoer"
version = "5.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86ad4c3a31123b6b4713c60390f0d5070555edf9ce7a9fe10ec4703432c6c413"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
