name = "Fabulously Optimized"
author = "robotkoer"
version = "5.2.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c6488a3eeeba0d141f635cbcd35ea7085a72c01e0ec8944e96c4e2a4fe7375d"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
