name = "Fabulously Optimized"
author = "robotkoer"
version = "5.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "628f0623112ac65fd7ac8717a3e6efd962fc17ebbd7459c0eb67f808bbdfd0e4"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
