name = "Fabulously Optimized"
author = "robotkoer"
version = "5.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f543723dcb08a6807e0869e2ae32a04a99d0ca034c030a8250dbf95085c3e6d2"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
