name = "Fabulously Optimized"
author = "robotkoer"
version = "11.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ed1c2e082bbfd627c2d9859b9b06156b299a5089c9fa2a68185296808cee9dc"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
