name = "Fabulously Optimized"
author = "robotkoer"
version = "11.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c757d0eb1cbe34f4fed5733ec3b0cd44464f182e904818b16e7224058cf03cab"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
