name = "Fabulously Optimized"
author = "robotkoer"
version = "11.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f765cccc4b6f728bc485089a2dcd5b8672472366ff497592ee7eddfe8fcd7e43"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
