name = "Fabulously Optimized"
author = "robotkoer"
version = "5.12.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07d03170a6c7aad57c7823370c1f14c0c086a7725367fb225bea644c1473c288"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
