name = "Fabulously Optimized"
author = "robotkoer"
version = "5.12.0-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56886325079197a0c19cc76378adbb9a8b51baece354b324fc43ae240cca86f9"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
