name = "Fabulously Optimized"
author = "robotkoer"
version = "5.12.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9632044fa00fa19373cef989ba758637686077cd37822f174c3f62f69ac89893"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
