name = "Fabulously Optimized"
author = "robotkoer"
version = "5.12.0-beta.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adeb6ec405957e3d10cebdd72762d966d242b28e6ead39c839b4bfc38e6011ef"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
