name = "Fabulously Optimized"
author = "robotkoer"
version = "5.12.0-beta.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23a82a9e2631894a90ca0f5bb85695d92d2cab070a3d024bab0bfbf379238d57"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
