name = "Fabulously Optimized"
version = "4.0.0-beta.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97dc1a5df5e8ce94ea345588be8a513bff807da63effcf512823a7bb3c9b83ea"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
