name = "Fabulously Optimized"
version = "4.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "896b5dbad9c470e92f542a022b9ac55205bce4fd19774976c77c7d95b5444154"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
