name = "Fabulously Optimized"
version = "4.0.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6390f1b56f7448ad0e7a19a0b5cd7e033b262458fbfe7682f1ae4d34b8535912"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
