name = "Fabulously Optimized"
version = "4.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2c20ffaf09f2cf1133de41b48afcb816504f24fcc5cfb7862078db86a076312"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
