name = "Fabulously Optimized"
version = "4.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "195f3fecc7d29310735dee4977134860f7c5bda04efbbd9bc56a0cdb4d08b0e3"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
