name = "Fabulously Optimized"
version = "3.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d829dd620b234de7ea50fea8f0b17d01f7485d30a6c8f723911f95f47dcf5fc"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
