name = "Fabulously Optimized"
version = "3.3.0-alpha.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61b9c66fcdddde89f72f20f2450d89d6824b2e48a526d4088b5dd2b09c5bb98a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
