name = "Fabulously Optimized"
version = "3.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "586da8aa364c7779d3712a7f06c60ce8963c14c31842687be9d4449caf4d095c"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
