name = "Fabulously Optimized"
version = "3.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93991d969df8cc74c230661b47febf9a1138d22f16adedb224073649ee1e4569"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
