name = "Fabulously Optimized"
version = "3.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2503d7dd44137631cd4b3e6e9bff34e148b7542b8ac83425143487deca86e909"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
