name = "Fabulously Optimized"
version = "3.6.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc5bbaae425c61a62750cde8506d109cc8d817d05ec121c96ada611067b001af"

[versions]
fabric = "0.14.2"
minecraft = "1.18.2"
