name = "Fabulously Optimized"
version = "3.3.0-beta.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df254fe4d8755883ecdd94c50c9ceb9dcbc921f5cecb7516e830e9cadcc529ea"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
