name = "Fabulously Optimized"
version = "3.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e535712c1c30e43572f024644288e2f525edc94d6cdaec87cfca4e0c501cd4e8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
