name = "Fabulously Optimized"
version = "3.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9291a330e359f9e05b4558712a20a8de3f11c4eda0c377ad91a3bcab0faeeae"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
