name = "Fabulously Optimized"
version = "3.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe6969a3f22a63f47a4156768557525360893dff3a0bdfbf215c0cf2f50f1662"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
