name = "Fabulously Optimized"
version = "3.3.0-beta.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84f3883f877edfdf0161e6b4bb75917dc6b180e245b00c4742f89884fdaf2b99"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
