name = "Fabulously Optimized"
version = "3.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08a306ae5b21873d1a1143d45f14348ae6509700efafefa0c1a6ed8be0e7170e"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
