name = "Fabulously Optimized"
version = "3.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8e69d7399ef5f4787bfeb55679481a7ac6804acd637dc2d624ebd2aabe36d5a"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
