name = "Fabulously Optimized"
version = "4.1.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23fd67656da38b8a106076584f4d8bcbb5eaccc357927c4ea8a75837f3cc0b96"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
