name = "Fabulously Optimized"
author = "robotkoer"
version = "10.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f47c53cc13a3039942f6de2e353dd08c8190533fc7fe421a73ce30900414b35c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
