name = "Fabulously Optimized"
author = "robotkoer"
version = "10.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e88f3c130ddca0b59e23a855e00a88dbc1751b3b2e0f71c4fcea0fab02761509"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
