name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5098f49df88f065b7f3be99d0b94ef223bd4f13957d0fbb162424b63bb249f1"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
