name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.0-alpha.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "038b8c8d71198dd6fc5a418e0d347f77badba5eb545795df119f8c7c3e920b07"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
