name = "Fabulously Optimized"
author = "robotkoer"
version = "4.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30b1369856bce824a549420895edeaae0c4b3213aa62ae95494688a241ac809c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
