name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "948babb58582e12e29fe5fb69872a2267702d557e0cf3f9e65a1479543ee452a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
