name = "Fabulously Optimized"
author = "robotkoer"
version = "4.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb60183df2be50da72035d100838513579ad96349cfc260b2f2b6a8fce463476"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
