name = "Fabulously Optimized"
author = "robotkoer"
version = "4.10.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7c9fb66a6365c9564bc887e81638facf17990e32584ddfc1032f2c2d708e801"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
