name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.0-alpha.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91713dadcbb558529e8d2af8c557fd3badf2156091c466e07557f1d03aa0ecd8"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
