name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dacf1349e6dc97b153eef12e024869a1117b25eaa391bb8f146ba1a0915b014"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
