name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.0-alpha.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e24e03f60198a6bda5ad47b4ff196a026c71d376c49fcddeaeab7eae7b25684"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
