name = "Fabulously Optimized"
author = "robotkoer"
version = "5.11.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4136f9946ba131da6160a5e7dd0f98fbed7cf3ea8a035d9526a71a8a00d570ea"

[versions]
fabric = "0.15.10"
minecraft = "1.20.5"
