name = "Fabulously Optimized"
author = "robotkoer"
version = "5.10.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cff28535b327846f8e644e0510e185ed41bd50b4ba8e4d7394a58e67408535d6"

[versions]
fabric = "0.15.10"
minecraft = "1.20.5"
